#pragma once

#ifndef __CLIENT_ENUM_H__
#define __CLIENT_ENUM_H__

enum class ESceneType{ SCENE_LOGO, SCENE_STAGE1, SCENE_STAGE2, SCENE_LOADING, SCENE_BOSS, SCENE_END };
enum class LOADINGID { LOADING_STAGE1, LOADING_STAGE2, LOADING_BOSS, LOADING_END };

enum class RESOURCETYPE { RESOURCE_BUFFER, RESOURCE_TEXTURE, RESOURCE_END };

//enum class LAYERID { LAYER_ENVIRONMENT, LAYER_GAMELOGIC, LAYER_UI, LAYER_END };


#endif // !__CLIENT_ENUM_H__
